### PR TITLE
Feature: reset if files under watch changed

### PR DESCRIPTION
**Pull request by tin-nl**
This automagically resets the emulation in Hatari if the debugged binary (or: any given file under watch) changes. Heads up: symbols aren't handled in a gracefull way atm - as in: they are not re-loaded from the new binary; so symbol handling still needs some thought for this to be ready for prime-time, but the feature is pretty helpful as-is, still.

### CODE REVIEW

**Comment by kareandersen** [comment]
Now we're talking workflow! Looking forward to testing this in practice.

**Comment by kareandersen** [comment]
Does not build cleanly on Mac OS/arm64 tho:

Undefined symbols for architecture arm64:
  "FileWatcher::clear()", referenced from:
      LaunchHatari(LaunchSettings const&, Session const*) in launcher.o
  "FileWatcher::addPath(QString const&)", referenced from:
      LaunchHatari(LaunchSettings const&, Session const*) in launcher.o
  "FileWatcher::addPaths(QStringList const&)", referenced from:
      LaunchHatari(LaunchSettings const&, Session const*) in launcher.o
  "FileWatcher::FileWatcher(Session const*)", referenced from:
      Session::createFileWatcherInstance() in session.o
ld: symbol(s) not found for architecture arm64

**Comment by kareandersen** [comment]
Problem solved:

diff --git a/tools/hrdb/hrdb.pro b/tools/hrdb/hrdb.pro
index 1c92961f..d4a9de53 100644
--- a/tools/hrdb/hrdb.pro
+++ b/tools/hrdb/hrdb.pro
@@ -35,6 +35,7 @@ SOURCES += \
     models/symboltable.cpp \
     models/symboltablemodel.cpp \
     models/targetmodel.cpp \
+    models/filewatcher.cpp \
     transport/dispatcher.cpp \
     ui/addbreakpointdialog.cpp \
     ui/breakpointswidget.cpp \
@@ -73,6 +74,7 @@ HEADERS += \
     models/symboltable.h \
     models/symboltablemodel.h \
     models/targetmodel.h \
+    models/filewatcher.h \
     transport/dispatcher.h \
     transport/remotecommand.h \
     ui/addbreakpointdialog.h \

**Comment by tin-nl** [comment]
Thanks for the heads up & fix @kareandersen - I'm using @ggnkua's awesome fastbuild config (see https://github.com/ggnkua/hatari/tree/debugger-extensions/fastbuild) to not to have to put up with qmake et al. anymore - so I _totally_ forgot about that project file.

**Comment by tattlemuss** [comment]
I've merged this pull request -- thanks!

One problem I have noticed is something like this:
- Launch the prg with the file watcher
- Exit hatari but leave hrdb open
- Launch hatari by some other method (e.g. running something else)
- Touch the watched file and it resets the new hatari instance!

This is obviously a bit niche but I wonder if there is a way to avoid this, e.g. by limiting the file watcher to the hatari instance that was launched. Might need to have a think.

**Pull request merged**
